import { Post } from "@/types";

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    timestamp: "2024-03-10T14:30:00Z",
    university: "İstanbul Teknik Üniversitesi",
    universityId: "115069",
    username: "user123",
    upvotes: 42,
    downvotes: 3,
    commentsCount: 7,
    isPrivate: false,
  },
  {
    id: "2",
    content:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    timestamp: "2024-02-15T09:20:00Z",
    university: "Boğaziçi Üniversitesi",
    universityId: "105322",
    username: "campusLife",
    upvotes: 28,
    downvotes: 1,
    commentsCount: 4,
    isPrivate: false,
  },
  {
    id: "3",
    content:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.",
    timestamp: "2024-01-05T16:45:00Z",
    university: "Orta Doğu Teknik Üniversitesi",
    universityId: "122571",
    username: "techStudent",
    upvotes: 56,
    downvotes: 4,
    commentsCount: 12,
    isPrivate: false,
  },
  {
    id: "4",
    content:
      "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    timestamp: "2024-02-28T11:15:00Z",
    university: "Hacettepe Üniversitesi",
    universityId: "113082",
    username: "medStudent",
    upvotes: 33,
    downvotes: 2,
    commentsCount: 6,
    isPrivate: true,
  },
  {
    id: "5",
    content:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.",
    timestamp: "2023-11-20T10:30:00Z",
    university: "Ankara Üniversitesi",
    universityId: "102738",
    username: "scholar22",
    upvotes: 19,
    downvotes: 5,
    commentsCount: 3,
    isPrivate: false,
  },
  {
    id: "6",
    content:
      "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
    timestamp: "2024-01-25T13:40:00Z",
    university: "Ege Üniversitesi",
    universityId: "109290",
    username: "izmir35",
    upvotes: 45,
    downvotes: 3,
    commentsCount: 8,
    isPrivate: false,
  },
  {
    id: "7",
    content:
      "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
    timestamp: "2024-02-10T17:20:00Z",
    university: "Yıldız Teknik Üniversitesi",
    universityId: "126982",
    username: "engineerX",
    upvotes: 37,
    downvotes: 6,
    commentsCount: 5,
    isPrivate: true,
  },
  {
    id: "8",
    content:
      "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.",
    timestamp: "2024-03-05T08:50:00Z",
    university: "Sabancı Üniversitesi",
    universityId: "123400",
    username: "privateCampus",
    upvotes: 64,
    downvotes: 2,
    commentsCount: 15,
    isPrivate: false,
  },
  {
    id: "9",
    content:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat.",
    timestamp: "2024-01-15T19:10:00Z",
    university: "Koç Üniversitesi",
    universityId: "118853",
    username: "student99",
    upvotes: 51,
    downvotes: 4,
    commentsCount: 9,
    isPrivate: false,
  },
  {
    id: "10",
    content:
      "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit.",
    timestamp: "2024-02-20T12:25:00Z",
    university: "Galatasaray Üniversitesi",
    universityId: "111395",
    username: "gsStudent",
    upvotes: 29,
    downvotes: 1,
    commentsCount: 6,
    isPrivate: false,
  },
];
