import PageTitle from "@/components/PageTitle";
import CreatePost from "../components/CreatePost";
import Post from "../components/Post";
import { House } from "lucide-react";

const MOCK_POSTS = [
  {
    id: "1",
    content: "Bugün kampüste harika bir etkinliğe katıldım!",
    timestamp: "2024-03-10T15:30:00Z",
    university: "İstanbul Üniversitesi",
    username: "kampus123",
    upvotes: 15,
    downvotes: 2,
    commentsCount: 3,
    isPrivate: false,
  },
  {
    id: "2",
    content: "Final haftası yaklaşıyor, herkes hazır mı?",
    timestamp: "2024-03-10T14:20:00Z",
    university: "Boğaziçi Üniversitesi",
    upvotes: 25,
    downvotes: 1,
    commentsCount: 8,
    isPrivate: true,
  },
  {
    id: "3",
    content: "Bugün dersim iptal oldu, çok şanslıyım!",
    timestamp: "2024-03-10T13:45:00Z",
    university: "Koç Üniversitesi",
    username: "ozguro",
    upvotes: 18,
    downvotes: 3,
    commentsCount: 5,
    isPrivate: false,
  },
  {
    id: "4",
    content: "Yaz tatili planları yapmaya başladım, önerilerinizi bekliyorum!",
    timestamp: "2024-03-10T12:00:00Z",
    university: "Sabancı Üniversitesi",
    username: "lale_34",
    upvotes: 12,
    downvotes: 1,
    commentsCount: 6,
    isPrivate: true,
  },
  {
    id: "5",
    content:
      "Bugün kütüphaneye gitmeyi planlıyorum, hangi kitapları önerirsiniz?",
    timestamp: "2024-03-09T16:10:00Z",
    university: "İstanbul Teknik Üniversitesi",
    username: "kitapci_37",
    upvotes: 30,
    downvotes: 2,
    commentsCount: 10,
    isPrivate: false,
  },
  {
    id: "6",
    content:
      "Bu dönemin en zorlu dersini geçtim, başarıya ulaşmanın keyfi başka!",
    timestamp: "2024-03-09T15:30:00Z",
    university: "Boğaziçi Üniversitesi",
    username: "deniz_99",
    upvotes: 40,
    downvotes: 5,
    commentsCount: 12,
    isPrivate: false,
  },
  {
    id: "7",
    content: "Bugün arkadaşlarla yemek yedim, çok eğlenceliydi!",
    timestamp: "2024-03-09T14:00:00Z",
    university: "İstanbul Üniversitesi",
    username: "mert_x",
    upvotes: 10,
    downvotes: 1,
    commentsCount: 2,
    isPrivate: false,
  },
  {
    id: "8",
    content: "Akademik danışmanımla görüşmem çok verimli geçti.",
    timestamp: "2024-03-09T13:00:00Z",
    university: "Koç Üniversitesi",
    username: "hakan_42",
    upvotes: 20,
    downvotes: 3,
    commentsCount: 4,
    isPrivate: true,
  },
  {
    id: "9",
    content:
      "Final haftasına sıkı bir şekilde çalışıyorum, motivasyonum zirveye çıktı!",
    timestamp: "2024-03-08T18:30:00Z",
    university: "Sabancı Üniversitesi",
    username: "buse_83",
    upvotes: 28,
    downvotes: 2,
    commentsCount: 7,
    isPrivate: false,
  },
  {
    id: "10",
    content: "Tüm proje grubu toplantıya girecek, birlikte başarılı olacağız!",
    timestamp: "2024-03-08T17:50:00Z",
    university: "İstanbul Teknik Üniversitesi",
    username: "ayse_t",
    upvotes: 22,
    downvotes: 4,
    commentsCount: 5,
    isPrivate: true,
  },
  {
    id: "11",
    content: "Bugün çok önemli bir seminer vardı, çok şey öğrendim.",
    timestamp: "2024-03-08T16:40:00Z",
    university: "Boğaziçi Üniversitesi",
    username: "melis_s",
    upvotes: 35,
    downvotes: 3,
    commentsCount: 8,
    isPrivate: false,
  },
  {
    id: "12",
    content: "Hava çok güzel, dışarıda bir yürüyüş yapmayı planlıyorum.",
    timestamp: "2024-03-08T15:00:00Z",
    university: "İstanbul Üniversitesi",
    username: "gokhan_23",
    upvotes: 12,
    downvotes: 2,
    commentsCount: 3,
    isPrivate: false,
  },
  {
    id: "13",
    content: "Kampüste bir etkinlik düzenleniyor, mutlaka katılmalısınız!",
    timestamp: "2024-03-07T19:00:00Z",
    university: "Koç Üniversitesi",
    username: "serdar_29",
    upvotes: 17,
    downvotes: 1,
    commentsCount: 6,
    isPrivate: false,
  },
  {
    id: "14",
    content: "Sınav stresiyle başa çıkmak için yoga yapmaya başladım.",
    timestamp: "2024-03-07T18:15:00Z",
    university: "Sabancı Üniversitesi",
    username: "selin_87",
    upvotes: 15,
    downvotes: 4,
    commentsCount: 5,
    isPrivate: true,
  },
  {
    id: "15",
    content: "Bugün yeni bir ders aldım, oldukça heyecanlıyım.",
    timestamp: "2024-03-07T17:00:00Z",
    university: "İstanbul Teknik Üniversitesi",
    username: "mehmet_71",
    upvotes: 40,
    downvotes: 1,
    commentsCount: 9,
    isPrivate: false,
  },
  {
    id: "16",
    content: "Ödevimi bitirdim, rahat bir nefes aldım.",
    timestamp: "2024-03-07T16:30:00Z",
    university: "Boğaziçi Üniversitesi",
    username: "beyza_56",
    upvotes: 25,
    downvotes: 0,
    commentsCount: 4,
    isPrivate: false,
  },
  {
    id: "17",
    content:
      "Bugün okulda çok keyifli bir gün geçirdim, arkadaşlarımla çok eğlendim!",
    timestamp: "2024-03-06T18:45:00Z",
    university: "İstanbul Üniversitesi",
    username: "yusuf_78",
    upvotes: 18,
    downvotes: 2,
    commentsCount: 7,
    isPrivate: false,
  },
  {
    id: "18",
    content: "Çalışmalarımda ilerleme kaydettim, çok verimli bir gün oldu.",
    timestamp: "2024-03-06T17:20:00Z",
    university: "Koç Üniversitesi",
    username: "seda_64",
    upvotes: 22,
    downvotes: 1,
    commentsCount: 5,
    isPrivate: true,
  },
  {
    id: "19",
    content: "Bugün kampüs içinde yeni bir kafe açıldı, mutlaka uğrayın!",
    timestamp: "2024-03-06T16:00:00Z",
    university: "Sabancı Üniversitesi",
    username: "omer_92",
    upvotes: 30,
    downvotes: 2,
    commentsCount: 10,
    isPrivate: false,
  },
  {
    id: "20",
    content: "Derslerimin büyük kısmını bitirdim, artık rahatım!",
    timestamp: "2024-03-06T14:30:00Z",
    university: "İstanbul Teknik Üniversitesi",
    username: "can_45",
    upvotes: 20,
    downvotes: 1,
    commentsCount: 6,
    isPrivate: true,
  },
];

export default function Home() {
  return (
    <div className="">
      <PageTitle title="Ana Sayfa" icon={House} />
      <CreatePost />
      <div className="sm:space-y-4">
        {MOCK_POSTS.map((post) => (
          <Post key={post.id} {...post} />
        ))}
      </div>
    </div>
  );
}
